### ISSUE TITLE
Main Thread Reported Blocked when idle

### ISSUE THREAD

**Issue by bhedge** [tj/node-blocked#13]
Want to start off by saying thank you for providing this library...  while troubleshooting a main thread blocking issue in a Koa app and we systematically removed each element of the app from our server.js file only to find that the main thread will report blocked with the simplest of Node apps.

With either of these code samples in node version 9.8.0:
```
const Koa = require('koa');
const app = new Koa();

const blocked = require('blocked');
blocked(function(ms) {
    console.log(`!!! >>> MAIN THREAD Blocked for ${ms}ms.`);
}, {threshold:10});

app.use(ctx => {
  ctx.body = '{"debug":"return from debug"}';
});
app.listen(4000);
```

or

```
const http = require('http')
const port = 4000

const blocked = require('blocked');
blocked(function(ms) {
    console.log(`!!! >>> MAIN THREAD Blocked for ${ms}ms.`);
}, {threshold:10});

const requestHandler = (request, response) => {
  response.end('{"debug":"return from debug"}')
}

const server = http.createServer(requestHandler)

server.listen(port, (err) => {
  if (err) {
    return console.log('error:', err)
  }

  console.log(`http server listening on port: ${port}`)
})
```

With output:
```
http server listening on port: 4000
!!! >>> MAIN THREAD Blocked for 35ms.
!!! >>> MAIN THREAD Blocked for 30ms.
!!! >>> MAIN THREAD Blocked for 45ms.
!!! >>> MAIN THREAD Blocked for 18ms.
!!! >>> MAIN THREAD Blocked for 11ms.
!!! >>> MAIN THREAD Blocked for 11ms.
!!! >>> MAIN THREAD Blocked for 36ms.
...
```

With either of the code sample above, the main thread will report blocked when the application is idle with no requests inbound to the web server and this points to a node.js internal blocking or node-blocked is misreporting blocking in certain instances. I am new to this level of internals and apologize if this is a known item.

**Are there false positives with node-blocked or are we potentially seeing issues within the node core internals?**

**Comment by bhedge** [comment]
When using blocked-at we had to tune the threshold down very low with the following code:

```
const http = require('http')
const port = 4000

const blockedAt = require('blocked-at');
blockedAt((time, stack) => {
    console.log(`Blocked for ${time}ms, operation started here:`, stack)
},  {threshold:1, trimFalsePositives:true});

const requestHandler = (request, response) => {
  response.end('{"debug":"return from debug"}')
}

const server = http.createServer(requestHandler)

server.listen(port, (err) => {
  if (err) {
    return console.log('error:', err)
  }

  console.log(`http server listening on port: ${port}`)
})
```

But we saw many false positives with the blocked-at code itself and a few items from the node internals:

```
Blocked for 2.17335595703125ms, operation started here: [ '    at HTTPParser.emitInitNative (internal/async_hooks.js:131:43)',
  '    at connectionListenerInternal (_http_server.js:336:10)',
  '    at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)',
  '    at Server.connectionListener (_http_server.js:313:3)',
  '    at Server.emit (events.js:180:13)',
  '    at TCP.onconnection (net.js:1558:8)' ]
```

We want to ensure we can accurately detect main thread blocking as we add each of the elements back to our app and wanted to ask your thoughts on the accuracy of these methods to observe main thread blocking.
